#!/bin/bash

# Code setup script.

set -euo pipefail

# === START CODE SETUP =====================================================

# code profile
cp -rf /setup/profile/settings.json ~/.local/share/code-server/User/settings.json

# code extensions
cp -rf /setup/extensions/extensions.json /home/user/.local/share/code-server/extensions/extensions.json

# === END CODE SETUP =======================================================


